modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="custom_taming_framework"
version="${file.jarVersion}"
displayName="Custom Taming Framework"
logoFile="logo.png"
authors="Pycoder"
description='''
自定义驯兽框架
'''

[[dependencies.custom_taming_framework]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.custom_taming_framework]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

